Repository Chainlit/chainlit, pull requests merged in 2024-11, with the labels that each got.

#1501 fix #1230 Incorrect message ordering in UI
  libs/react-client/src/types/file.ts
  libs/react-client/src/useChatInteract.ts
  libs/react-client/src/useChatSession.ts
Labels: bug, frontend, size:XS

#1406 feat: add audio presence to copilot header
  libs/copilot/src/components/Header.tsx
Labels: enhancement, frontend, size:M

#1493 Update dependencies to address security issues
  .github/workflows/pytest.yaml
  backend/poetry.lock
  backend/pyproject.toml
Labels: security, review-me, size:XS

#1495 Significant pre-commit/CI improvements
  .github/workflows/ci.yaml
  .github/workflows/lint-backend.yaml
  .gitignore
  .husky/pre-commit
  backend/build.py
  backend/chainlit/cache.py
  backend/poetry.lock
  backend/pyproject.toml
  lint-staged.config.js
  package.json
  pnpm-lock.yaml
Labels: dev-tooling, review-me, size:L

#1468 Add missing wait in chat_profiles test
  cypress/e2e/chat_profiles/spec.cy.ts
Labels: size:S, e2e-tests

#1503 Allow running commit hooks outside of poetry/venv.
  lint-staged.config.js
Labels: dev-tooling, review-me, size:XS

#1463 @data_layer API hook to configure data layer.
  backend/chainlit/__init__.py
  backend/chainlit/callbacks.py
  backend/chainlit/config.py
  backend/chainlit/data/__init__.py
  backend/tests/conftest.py
  backend/tests/data/test_get_data_layer.py
  backend/tests/test_callbacks.py
  backend/tests/test_server.py
  cypress/e2e/custom_data_layer/sql_alchemy.py
  cypress/e2e/data_layer/main.py
  cypress/e2e/data_layer/spec.cy.ts
Labels: data layer, backend, architecture, review-me, size:L, e2e-tests, unit-tests

#1530 Actually run eslint ;)
  frontend/src/components/atoms/buttons/githubButton.tsx
  frontend/src/components/atoms/inputs/SliderInput.tsx
  frontend/src/components/molecules/auth/AuthLogin.tsx
  frontend/src/hooks/useUpload.tsx
  libs/copilot/package.json
  libs/react-client/package.json
  libs/react-client/src/types/element.ts
  libs/react-client/src/utils/token.ts
  package.json
  pnpm-lock.yaml
Labels: review-me, size:M

#1529 feat: use async lc tracer instead of run_sync
  backend/chainlit/langchain/callbacks.py
Labels: evaluate-with-priority, backend, size:L

#1531 Ruff All the Things
  backend/build.py
  backend/chainlit/__init__.py
  backend/chainlit/action.py
  backend/chainlit/auth.py
  backend/chainlit/chat_context.py
  backend/chainlit/chat_settings.py
  backend/chainlit/config.py
  backend/chainlit/context.py
  backend/chainlit/data/acl.py
  backend/chainlit/data/base.py
  backend/chainlit/data/dynamodb.py
  backend/chainlit/data/literalai.py
  backend/chainlit/data/sql_alchemy.py
  backend/chainlit/data/storage_clients/azure.py
  backend/chainlit/data/storage_clients/s3.py
  backend/chainlit/discord/app.py
  backend/chainlit/element.py
  backend/chainlit/emitter.py
  backend/chainlit/haystack/callbacks.py
  backend/chainlit/input_widget.py
  backend/chainlit/langchain/callbacks.py
  backend/chainlit/langflow/__init__.py
  backend/chainlit/llama_index/callbacks.py
  backend/chainlit/message.py
  backend/chainlit/mistralai/__init__.py
  backend/chainlit/oauth_providers.py
  backend/chainlit/openai/__init__.py
  backend/chainlit/secret.py
  backend/chainlit/server.py
  backend/chainlit/session.py
  backend/chainlit/slack/app.py
  backend/chainlit/socket.py
  backend/chainlit/step.py
  backend/chainlit/sync.py
  backend/chainlit/teams/app.py
  backend/chainlit/types.py
  backend/chainlit/utils.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/data/conftest.py
  backend/tests/data/storage_clients/test_s3.py
  backend/tests/data/test_literalai.py
  backend/tests/data/test_sql_alchemy.py
  backend/tests/llama_index/test_callbacks.py
  backend/tests/test_callbacks.py
  backend/tests/test_context.py
  backend/tests/test_emitter.py
  backend/tests/test_server.py
  cypress/e2e/elements/main.py
  lint-staged.config.js
Labels: review-me, size:L

#1533 Fixup in E2E tests
  cypress.config.ts
  cypress/support/testUtils.ts
Labels: review-me, size:XS

#1534 Various tweaks to data_layer acquisition logic.
  backend/chainlit/data/__init__.py
Labels: data layer, review-me, size:M

#1508 Bump version to 2.1, changelog for unreleased @data_layer
  CHANGELOG.md
  backend/pyproject.toml
Labels: review-me, size:S

#1525 Update oauth_providers.py to include Keycloak
  backend/chainlit/oauth_providers.py
Labels: auth, backend, size:M

#1547 Revert "feat: chainlit option to require websocket"
  libs/react-client/README.md
  libs/react-client/src/useChatSession.ts
Labels: size:M
