Repository Chainlit/chainlit, pull requests merged in 2024-09, with the labels that each got.

#1271 Various improvements in tests/CI
  .github/actions/poetry-python-install/action.yaml
  .github/workflows/e2e-tests.yaml
  .github/workflows/mypy.yaml
  .github/workflows/pytest.yaml
Labels: enhancement, dev-tooling

#1289 Changelog for version 1.2.0.
  CHANGELOG.md
Labels: dev-tooling, review-me

#1221 BUGFIX | SQLAlchemy - Fix show_input on chat resume
  backend/chainlit/data/sql_alchemy.py
Labels: bug, data layer

#1285 [fix] `LlamaIndexCallbackHandler` to support displaying function calls as tools in CoTs
  backend/chainlit/llama_index/callbacks.py
  backend/tests/llama_index/test_callbacks.py
Labels: bug

#1303 Correct release version in changelog.
  CHANGELOG.md
Labels: review-me

#1306 Test fastapi matrix
  .github/workflows/pytest.yaml
  backend/poetry.lock
  backend/pyproject.toml
Labels: review-me

#1270 E2e remove wait
  cypress/e2e/action/spec.cy.ts
  cypress/e2e/ask_user/spec.cy.ts
  cypress/e2e/stop_task/spec.cy.ts
  cypress/support/testUtils.ts
Labels: dev-tooling, review-me

#1293 Documenting release engineering.
  RELENG.md
Labels: dev-tooling, review-me

#1144 Added missing feedback_id.
  backend/chainlit/data/sql_alchemy.py
Labels: enhancement, data layer, review-me

#1276 Resolve #1256 - Fix Interaction Issues with Chat Profile Description Popover
  cypress/e2e/chat_profiles/main.py
  cypress/e2e/chat_profiles/spec.cy.ts
  frontend/src/components/molecules/chatProfiles.tsx
Labels: bug

#1288 Data layer cleanup
  backend/chainlit/data/__init__.py
  backend/chainlit/data/base.py
  backend/chainlit/data/dynamodb.py
  backend/chainlit/data/literalai.py
  backend/chainlit/data/sql_alchemy.py
  backend/chainlit/data/storage_clients.py
  backend/chainlit/data/utils.py
  backend/chainlit/session.py
  cypress/e2e/data_layer/main.py
Labels: backend, architecture, review-me

#1292 Factor out callbacks and extensive test coverage.
  backend/chainlit/__init__.py
  backend/chainlit/callbacks.py
  backend/chainlit/config.py
  backend/tests/conftest.py
  backend/tests/llama_index/test_callbacks.py
  backend/tests/test_callbacks.py
  backend/tests/test_context.py
  backend/tests/test_emitter.py
  backend/tests/test_user_session.py
Labels: backend, dev-tooling, architecture, review-me

#1291 Bump dataclasses to latest version.
  backend/poetry.lock
  backend/pyproject.toml
Labels: backend, review-me

#1337 fix: websocket connection when submounting chainlit
  backend/chainlit/config.py
  backend/chainlit/langchain/callbacks.py
  backend/chainlit/server.py
  backend/chainlit/utils.py
  backend/tests/conftest.py
  backend/tests/test_callbacks.py
Labels: evaluate-with-priority

#1346 1.2.0 Hotfix - Add get_element() to sql_alchemy.py
  backend/chainlit/data/sql_alchemy.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/conftest.py
  backend/tests/data/__init__.py
  backend/tests/data/conftest.py
  backend/tests/data/test_sql_alchemy.py
Labels: evaluate-with-priority

#1382 Don't run code on importing data module
  backend/chainlit/data/__init__.py
Labels: data layer, backend, review-me, size:S
