Repository Chainlit/chainlit, pull requests merged in 2025-09, with the labels that each got.

#2504 fix: async e2e spec entry point name
  cypress/support/run.ts
Labels: dev-tooling, size:XS

#2512 fix: take overridden config into account in audio handlers
  backend/chainlit/socket.py
Labels: bug, size:S

#2511 chore: release
  CHANGELOG.md
  backend/chainlit/version.py
Labels: size:S

#2514 docs: fix changelog of latest release
  CHANGELOG.md
Labels: size:XS

#2521 refactor: allow Thread Sharing by user-defined callback
  backend/chainlit/server.py
Labels: auth, size:XS

#2555 fix: properly finalize data layer
  backend/chainlit/data/base.py
  backend/chainlit/data/chainlit_data_layer.py
  backend/chainlit/data/dynamodb.py
  backend/chainlit/data/literalai.py
  backend/chainlit/data/sql_alchemy.py
  backend/chainlit/data/storage_clients/azure.py
  backend/chainlit/data/storage_clients/azure_blob.py
  backend/chainlit/data/storage_clients/base.py
  backend/chainlit/data/storage_clients/gcs.py
  backend/chainlit/data/storage_clients/s3.py
  backend/chainlit/server.py
  cypress/e2e/data_layer/main.py
  cypress/e2e/thread_resume/main.py
Labels: data layer, backend, size:L
